# Generated by Django 4.2.26 on 2025-11-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPTAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('api_key', models.CharField(max_length=500, unique=True)),
                ('webhook_url', models.URLField(help_text='Endpoint to send response back to', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GPT Account',
                'verbose_name_plural': 'GPT Accounts',
                'ordering': ['-created_at'],
            },
        ),
    ]
