# Generated by Django 4.2.26 on 2025-11-10 04:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Market name/title', max_length=500)),
                ('level', models.IntegerField(default=0, help_text='Depth level: 0=root, 1=first level, 2=second level')),
                ('status', models.CharField(choices=[('pending', 'Pending Analysis'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('data', models.JSONField(default=dict, help_text='\n        Stores all economic data:\n        {\n            "value_added_usd": float,\n            "employment_count": int,\n            "rationale": str,\n            "sub_markets": [\n                {\n                    "name": str,\n                    "value_added_usd": float,\n                    "employment_count": int,\n                    "rationale": str\n                }\n            ],\n            "metadata": {\n                "analysis_date": str,\n                "llm_response": str,\n                "chat_id": str,\n                "request_id": str\n            }\n        }\n        ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_nodes', to='account.gptaccount')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='market.marketnode')),
            ],
            options={
                'verbose_name': 'Market Node',
                'verbose_name_plural': 'Market Nodes',
                'ordering': ['level', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketAnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_nodes', models.IntegerField(default=0)),
                ('completed_nodes', models.IntegerField(default=0)),
                ('failed_nodes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_jobs', to='account.gptaccount')),
                ('root_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='market.marketnode')),
            ],
            options={
                'verbose_name': 'Market Analysis Job',
                'verbose_name_plural': 'Market Analysis Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='marketnode',
            index=models.Index(fields=['account', 'level'], name='market_mark_account_0e72bb_idx'),
        ),
        migrations.AddIndex(
            model_name='marketnode',
            index=models.Index(fields=['parent', 'status'], name='market_mark_parent__f9e1c3_idx'),
        ),
        migrations.AddIndex(
            model_name='marketnode',
            index=models.Index(fields=['status', 'level'], name='market_mark_status_5d500b_idx'),
        ),
    ]
