# Generated by Django 4.2.7 on 2025-11-10 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketnode",
            name="message_request",
            field=models.ForeignKey(
                blank=True,
                help_text="The MessageRequest used to analyze this node",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="market_nodes",
                to="chat.messagerequest",
            ),
        ),
        migrations.AddField(
            model_name="marketnode",
            name="retry_count",
            field=models.IntegerField(
                default=0, help_text="Number of times this node has been retried"
            ),
        ),
        migrations.AlterField(
            model_name="marketnode",
            name="level",
            field=models.IntegerField(
                default=0,
                help_text="Depth level: 0=root, 1=first level, 2=second level, 3=third level",
            ),
        ),
    ]
