# Generated by Django 4.2.7 on 2025-11-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0002_marketnode_message_request_marketnode_retry_count_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="marketnode",
            constraint=models.UniqueConstraint(
                condition=models.Q(("message_request__isnull", False)),
                fields=("message_request",),
                name="unique_message_request_per_node",
            ),
        ),
    ]
