# Generated by Django 4.2.26 on 2025-11-10 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('market', '0003_marketnode_unique_message_request_per_node'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='marketnode',
            name='unique_message_request_per_node',
        ),
        migrations.AlterField(
            model_name='marketnode',
            name='message_request',
            field=models.OneToOneField(blank=True, help_text='The MessageRequest used to analyze this node', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_node', to='chat.messagerequest'),
        ),
    ]
