# Generated by Django 4.2.26 on 2025-11-06 11:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(blank=True, help_text='ChatGPT website chat ID (filled by extension)', max_length=255, null=True, unique=True)),
                ('title', models.CharField(blank=True, help_text='Chat title (filled by extension)', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='account.gptaccount')),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('response_type', models.CharField(choices=[('thinking', 'Thinking'), ('auto', 'Auto'), ('instant', 'Instant')], default='auto', max_length=20)),
                ('thinking_time', models.CharField(choices=[('standard', 'Standard'), ('extended', 'Extended')], default='standard', help_text="Only applicable when response_type is 'thinking'", max_length=20)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('executing', 'Executing'), ('done', 'Done'), ('failed', 'Failed')], default='idle', max_length=20)),
                ('response', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_retrieved_at', models.DateTimeField(blank=True, help_text='Last time this request was retrieved via API', null=True)),
                ('webhook_sent', models.BooleanField(default=False)),
                ('webhook_sent_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_requests', to='account.gptaccount')),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='chat.chat')),
            ],
            options={
                'verbose_name': 'Message Request',
                'verbose_name_plural': 'Message Requests',
                'ordering': ['-queued_at'],
                'indexes': [models.Index(fields=['account', 'status'], name='chat_messag_account_44f263_idx'), models.Index(fields=['status', 'queued_at'], name='chat_messag_status_ca9a92_idx'), models.Index(fields=['chat'], name='chat_messag_chat_id_84003f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['chat_id'], name='chat_chat_chat_id_f5b672_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['account', '-updated_at'], name='chat_chat_account_00d57f_idx'),
        ),
    ]
